### ISSUE TITLE
パスワードを忘れたユーザーを暫定的に救済する機能

### ISSUE THREAD

**Issue by prettyhappycatty** [AtCoder-NoviSteps/AtCoderNoviSteps#1346]
## Description / 説明

- 管理者が、旧IDと新IDを設定して、回答データをコピーできる機能 
   -  管理画面に以下の画面を用意
      -  [source user id]テキストボックス、 [destination user id]テキストボックス、[実行]ボタン
   - 上記画面の動作
      - 実行ボタンを押すと、destinationの回答状況のデータが空の場合に限り、回答状況をコピーする。
        - コピー対象は、taskAnswerのみ（ユーザテーブルの情報などは書き換えない） 
      - 成功、失敗の情報を管理者に通知する。

## Motivation / 動機

- 現状、ユーザーIDとパスワードで認証しており、パスワードを忘れた際の救済策がない

## Other notes / その他

- 背景
   - 悪い人が、乗っ取ることは防ぎたい
   - IDが変わってしまうことは、乗っ取りのリスクと比べると許容できる
- 運用フロー
   - （ユーザ側）パスワードを忘れたユーザが対象のIDをNovistep運営に連絡
   - （システム管理側）運営は、「新しい空のアカウントを作って新しいアカウントのIDを運営に連絡してもらいたい旨」をユーザに連絡する
   - （ユーザ側）ユーザは、空のアカウントを作り、運営に作成した新しいアカウントのIDを連絡する。
   - （システム側）運営は、コピー機能を使ってもとのIDのデータを新しいIDのデータにコピー。完了したらユーザに連絡する。
- 今後
  - メールアドレスを登録したユーザに関しては、メールアドレスを利用したパスワードリセットの機能を提供していきたい（優先順位は要調整）  
  - パスワード変更については、パスワードリセット機能を使ってもらう。
  - 問題集の作成機能を一般ユーザに解放したら、作者情報もコピーできるようにする。

**Comment by prettyhappycatty** [comment]
案

<img width="1307" alt="スクリーンショット 2024-10-08 0 21 12" src="https://github.com/user-attachments/assets/b9dd61fd-84fc-4baf-b207-a1ddfea1ca9f">

**Comment by KATO-Hiro** [comment]
早速、UI案を作成していただき、ありがとうございます。とても助かります。

LGTMです。

2枚目でシステムの処理状況が表示されており、とても安心感がありますね！

**Comment by prettyhappycatty** [comment]
>問題集の作成機能を一般ユーザに解放したら、作者情報もコピーできるようにする。

願わくば、これの前に、パスワードリセット機能つけて、回復できるようにしたいですね！

**Comment by KATO-Hiro** [comment]
> 願わくば、これの前に、パスワードリセット機能つけて、回復できるようにしたいですね！ （問題集の作成などにはメールアドレスの登録を必須とするとか）

機能が増えるとコピーの対象も増えるので、希望者が多ければパスワードリセット機能の方がよさそうですね。
