### ISSUE TITLE
コミット前にLinterとFormatterのチェックができるようにしましょう

### ISSUE THREAD

**Issue by KATO-Hiro** [AtCoder-NoviSteps/AtCoderNoviSteps#297]
https://zenn.dev/claustra01/articles/7ef07e69ce60fa

**Comment by KATO-Hiro** [comment]
ありがとうございます。優先度を変更しました。

他のタスクなどとの兼ね合いもあると思いますが、あべみさんが実装される予定はありますでしょうか?

**Comment by prettyhappycatty** [comment]
終わりましたのでプルリクを送りました！

#306

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

このIssueは完了したと思っていいのでしょうか?

**Comment by prettyhappycatty** [comment]
完了で大丈夫です！
