### ISSUE TITLE
カバレージツールをインストールしましょう

### ISSUE THREAD

**Issue by prettyhappycatty** [AtCoder-NoviSteps/AtCoderNoviSteps#318]
## Description / 説明

- [coverage c8](https://reffect.co.jp/html/vitest#Coverage_c8)

## Motivation / 動機

- 

## Other notes / その他

-

**Comment by KATO-Hiro** [comment]
テスト周りの環境がさらに充実しそうですね！！

大昔に以下のサービスを少しだけ使ったことがありますが、どのようなサービス・ツールを導入される予定でしょうか?
https://about.codecov.io/

**Comment by prettyhappycatty** [comment]
説明欄にリンクつけたのですが文字を変更するのを忘れていました🤣
説明欄に書いたツールを入れようと思っています。
いづれプルリクエスト時にカバレージ100%を条件に入れたいです。

**Comment by KATO-Hiro** [comment]
教えていただき、ありがとうございます！！！
Vitest専用のツールがあるのですね。初めて知りました。

> いづれプルリクエスト時にカバレージ100%を条件に入れたいです。

ロジックだけでなく、UIもカバレッジ100%を目指される方針でしょうか?
（数年前に見た書籍では難しい場合もあると書かれていたな気もしますが、2023年現在では可能になっていると理解すればよろしいのでしょうか?）

**Comment by prettyhappycatty** [comment]
どの範囲をカバレージ100にするかは様子を見て判断、、、という感じかと思います。
コントリビュートしてくださる方が不安なく開発できるように、という感じで充実させていければと！

**Comment by KATO-Hiro** [comment]
ツールを導入できたと思いますので、closeしてもよろしいでしょうか?
