### ISSUE TITLE
TaskAnswerテーブルの作成と、problems/{task_id}の画面で保存する機能を作成しましょう

### ISSUE THREAD

**Issue by prettyhappycatty** [AtCoder-NoviSteps/AtCoderNoviSteps#321]
## Description / 説明

- [x] TaskAnswerテーブルの作成
- [x] ステータスをテーブルから取得
- [x] problems/{task_id}で、変更したステータスをデータベースに保存（ログインユーザのデータで作成）
- [x] problems/で、ログインしているユーザのステータスを、データベースから表示
- [x] プログレスバーのac countを、データベースのステータスの状態から反映

## Motivation / 動機

- 

## Other notes / その他

-

**Comment by prettyhappycatty** [comment]
テーブル案


model Answer {
  id        String
  task_id   String
  user_id   String
  status_id String?

  task   Task?             @relation(fields: [task_id], references: [task_id])
  user   User?             @relation(fields: [user_id], references: [id])
  status SubmissionStatus? @relation(fields: [status_id], references: [id])

  created_at DateTime @default(now())
  updated_at DateTime @updatedAt

  @@id([task_id, user_id])
  @@map("taskanswer")
}

model SubmissionStatus {
  id         String @id @unique
  label_name String
  image_path String

  TaskAnswer Answer[]

  @@map("submissionstatus")
}

TODO

- [ ] memoの文字数制限？
- [ ] image_pathというよりは、表示する時のclassに設定する値を持ってた方がいいのかも？

**Comment by prettyhappycatty** [comment]
ありがとうございます。

初回は一旦デフォルトのものだけあればいいかなと思いましたが、その想定だとisAcCountの設定をするなら、ユーザーidが必要になりますね。

たとえば、私はACと解説ACとWAで管理する、ひろひろさんはACとTLEで管理する、みたいに完全に個人別でしょうか？
インポートの機能が想定されている以上、最低でも本家のステータスは全員に用意するのではと考えているのですが、いかがでしょうか？

**Comment by prettyhappycatty** [comment]
idのユニークは入れてもいいですが、1対1と考えると、
ユーザーとタスクの複合キーのユニークにすることになるかと思います。

**Comment by prettyhappycatty** [comment]
スポンサーで許容文字数変わるの面白いですね！
メモ、 本家のSubmissionIdつけるなら、ソースの中に書いてしまえば良いという話もありますね。

**Comment by KATO-Hiro** [comment]
> ありがとうございます。 携帯からなので、コメントいくつかに分かれます。
> 
> 初回は一旦デフォルトのものだけあればいいかなと思いましたが、isAcCountの設定をする想定なら、ユーザーidが必要になりますね。（テーブル設計には載ってて、意図がわからなくて最低限保存、、、って考えたときに抜いていました）
> 
> たとえば、私はACと解説ACとWAで管理する、ひろひろさんはACとTLEで管理する、みたいに完全に個人別でしょうか？それとも全員に共通するようなステータスがあるイメージでしょうか。 インポートの機能が想定されている以上、最低でも本家のステータスは全員に用意するのではと考えているのですが、いかがでしょうか？

前回のけんちょんさんとの打ち合わせで確認しましたが、解答状況は全員共通でベースとなるもの + 任意でカスタマイズできるようにすると理解しています。

ベースとしては、AC、解説AC、WA、Trying (考察済み、未実装)、No Subの5種類です。

カスタマイズも多くて3種類程度ではないかと思っています。

**Comment by KATO-Hiro** [comment]
> idのユニークは入れてもいいですが、1対1と考えると、 ユーザーとタスクの複合キーのユニークにすることになるかと思います。

現状の仕様だと、ユニークキーを入れなくとも一意に定まりそうですね。

**Comment by KATO-Hiro** [comment]
> スポンサーで許容文字数変わるの面白いですね！ メモ、 本家のSubmissionIdつけるなら、ソースの中に書いてしまえば良いという話もありますね。
 
メモとソースが一緒のページにあった方が使い勝手も良さそうです。
また実装も、かなり省力化できそうだと思います。

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ソースをインポートする想定はあるのでしょうか？
（しない想定かと思っていました）

**Comment by prettyhappycatty** [comment]
> Trying (考察済み、未実装)

submissionに紐づかないケースがあるのですね。

**Comment by KATO-Hiro** [comment]
> > Trying (考察済み、未実装)
> 
> submissionに紐づかないケースがあるのですね。

前回の打ち合わせで、コメントいただいたパターンです。

おそらく、外出先（もしくは競プロ用のPCがない環境）で考察しておき、帰宅したら実装したい、みたいな感じだと推察しています。

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ログインユーザの取得方法がわかったので、
再度こちらのissueの、データベースから取得して表示と、ステータスの保存に手をつけようと思います。
前回と同じブランチ名になってしまって良いでしょうか？

**Comment by KATO-Hiro** [comment]
お手数をおかけしますが、実装をお願いします。

ブランチ名は前回と同じで大丈夫です🙆。

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
button_colorについてですが、今サンプルデータでは色コードで設定していますが、
problems/[slug]/+page.svelteでbutton_colorを使うと、UIのフレームワークからエラーが出るみたいです。
>Type 'string' is not assignable to type '"red" | "yellow" | "green" | "purple" | "blue" | "light" | "dark" | "primary" | "none" ||"alternative" | undefined'

上記の色に存在するものにサンプルデータを変えても良いでしょうか？
それとも、エラーが出ないような指定方法を探しますか？
（私が調べると時間がかかりそうなので一旦前者にしておきたいなと思っています、、、）

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

解答状況を表すプログレスバーの配色でも同じ問題に直面し、暫定的に以下のような対処をしました。いかがでしょうか?
（ただ、この方法が大変そうであれば、一旦デフォルトの配色で進めていただけますでしょうか?）

・tailwindcssの記法でボタンをベタ打ち（orSvelteコンポーネント）で用意
・条件に応じたカラーコードの文字列を返すヘルパーメソッドを用意
・Svelteコンポーネント内部のclass属性に変数でカラーコードの文字列を指定


https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/blob/main/src/lib/components/TaskList.svelte
https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/blob/main/src/lib/components/ThermometerProgressBar.svelte
https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/blob/main/src/lib/utils/task.ts

**Comment by prettyhappycatty** [comment]
ありがとうございます！
ひとまずそのままのsvelteファイルで存在する色で表示に反映されることを確認してからトライしてみます！（フロントエンドのキャッチアップが遅い、、、）

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
よろしくお願いいたします！

あべみさんのおかげで、アプリの機能実装が大きく進んでいます。

ごく短期間でさまざまなツールのキャッチアップだけでなく、プルリクエストの作成を爆速で進めていただいているので。


（現時点の私の立ち位置としては、あべみさんができるだけ快適に実装を進められるように、けんちょんさんとの打ち合わせで伺った微妙なニュアンスをお伝えすることやいただいた質問になるべく早く返信するのがいいのかなぁとも思っています。）

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ありがとうございます！
いつもすぐに質問にお答えいただき助かっています（お忙しいと思うので無理せず、、、）

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
SubmissionStatusと画面を繋いでいて気になった点が２点あります。

- [ ] ボタンのソート順をテーブルに用意した方が良さそう
    -  多分NoSub、WA、ACみたいな順がデフォルト、みたいな想定がありそうなので。ソートキーを準備した方が良さそう。
    - ユーザーオリジナルのボタンを用意した時にもどの順、と付けたくなると思う。
- [ ] デフォルトステータス用のテーブルと、ユーザーステータス用のテーブルを分けた方がいいか、同じでいいか設計検討必要そう。
   - 最初、同じテーブルで実現する方法を考えた時、デフォルトのAC使っていたステータスは、ユーザがACの色を変えたときに変更以前のステータスで保存したタスクがあった場合に、ACの色は変わるのかどうか（追従していくのか）？が分からず。ユーザーステータス用のテーブルを作って、デフォルトを継承する場合は継承するフラグをおくのが妥当なのかなあと考えています。
  （実装大変そう）

**Comment by KATO-Hiro** [comment]
ボタンがソートできると嬉しそうですね。テーブルのUIコンポーネントに属性を付与すれば実装できそうだと記憶しています。

> デフォルトステータス用のテーブルと、ユーザーステータス用のテーブルを分けた方がいいか、同じでいいか設計検討必要そう。

同じテーブルでis_defaultのような属性で識別するのはいかがでしょうか?

同じ状態であっても、ユーザ指定があれば上書きするという方針がいいのではないかと考えています。
ユーザ指定に追従するほうが一貫性や実装のしやすさの観点から良さそうだと思っていますが、あべみさんのご意見はいかがでしょうか?

また、デフォルトに戻す　というオプションも必要そうですね。

**Comment by prettyhappycatty** [comment]
>ボタンがソートできると嬉しそうですね。テーブルのUIコンポーネントに属性を付与すれば実装できそうだと記憶しています。
select 時にorderbyで指定すればその通り取ってこれるかなと思っています。

> 同じテーブルでis_defaultのような属性で識別するのはいかがでしょうか?

例ですが、やりたいのは以下かと思っています。
・元々「AC」「WA」「NS」がある
　select * from submissionstatus where is_default = TRUE
・元々あるACを、「自力AC」として青色のボタンにしたい
   insert into submissionstatus (user_id, status, 継承元) VALUES('hogehoge', '解説AC', 'AC')
・新しく、「解説AC」として緑色のボタンを作りたい
   insert into submissionstatus (user_id, status) VALUES('hogehoge', '解説AC')
・4種類のボタンを「自力AC」「解説AC」「WA」「NS」として、保存したい。
  表示するボタンは
　select * from submissionstatus where is_default = TRUE or user_id='hogehoge'
　から、
　select * from submissionstatus where is_default = TRUE and  status =（select 継承元 from submissionstatus where user_id='hogehoge'）を除いたもの
・4種類のステータスがproblems/で表示されるし、過去に「AC」で保存したものもそのまま表示できる
　select * from submissionstatus where is_default = TRUE or user_id='hogehoge'

こんな感じかなあ、、、難しい、、、
「デフォルトに戻す」とはどのようなことを想定していますか？

**Comment by KATO-Hiro** [comment]
ありがとうございます！！

具体例を示していただき、処理のイメージがかなりはっきりとしてきました。実装は、かなり大変そうでしょうか?

> 「デフォルトに戻す」とはどのようなことを想定していますか？

言葉足らずでした。すみません。

元々の配色とラベル名のみの状態にするという意図でした。

カスタマイズを希望されるユーザが初期状態に戻したいというのは、今回の場合にはコーナーケース的な使い方になってしまいそうでしょうか?
（もう一度カスタマイズするという観点なら、元の色とラベルを指定して更新するということと同じ気もしてきました）

**Comment by prettyhappycatty** [comment]
そうですね、、、
元に戻す、はカスタマイズしたものを論理削除で、既に登録したステータスはそのまま（もう一度張り替えれば状態は変わる）でいかがでしょうか？

バッチ的に既にあるステータスを張り替えるのはあんまりやりたくない。

**Comment by KATO-Hiro** [comment]
> 元に戻す、はカスタマイズしたものを論理削除で、既に登録したステータスはそのまま（もう一度張り替えれば状態は変わる）でいかがでしょうか？

ご提案いただいた方針で進めていただければと思います。

ただ、やや優先度は低めかと思っていますが、いかがでしょうか？
（身もふたもないようなコメントになってしまい、すみません）

**Comment by prettyhappycatty** [comment]
はい。優先度低いと思っています。
ユーザカスタマイズについては、一応考えておいて、実装はまた後で、、、と思っています。

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
テーブルのupdateに苦労してて遅くなりました。
pushしたものにビルドエラーが出ていて、ローカルでは問題ないのですが、
解決策はあるでしょうか？
tsconfigがない、と言われてそうです。
>Warning: G] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:13:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


何か、prisma周りのコマンド実行し忘れでしょうかね、、、

**Comment by prettyhappycatty** [comment]
今回実施したのは以下の項目です。

- problems/{task_id}で、変更したステータスをデータベースに保存（ログインユーザのデータで作成）
- problems/で、ログインしているユーザのステータスを、データベースから表示
- プログレスバーのac countを、データベースのステータスの状態から反映

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
.fabricaを、src以下に入れることは可能でしょうか？

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
返信が遅くなり、すみません🙇。
難易度の高い部分の実装を進めていただき、ありがとうございます！！

本番環境DBに最新のスキーマが反映されていない可能性もあるため、確認してみます。
調査などにお手数をおかけしてしまい、申し訳ございません。


> .fabricaを、src以下に入れることは可能でしょうか？
はい。
公式ドキュメントではsrcに配置されていますし、変更しても影響は少ないのではないかと思っています。
（むしろ、手元のdb pushでエラーが出ているのは、現状の配置が原因の可能性もあります。要調査です。）

.fabricaが現状の配置になっているのは、導入した当初はPrismaとの関連が深そうと考えていたためです。

https://github.com/Quramy/prisma-fabbrica?tab=readme-ov-file#generator-configuration

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ありがとうございます。
.fabbricaの位置を３通りで試して見たけれどどれもダメでした。（アクセスはできるけどdefineXXXfactoryのインポートに失敗する）

＞本番環境DBに最新のスキーマが反映されていない可能性もあるため、確認してみます。

ありがとうございます。よろしくお願いします。prisma以下や.fabbricaにうまくアクセスできないのかな、と考えているのと、
エラーメッセージのRollupが〜が気になって調べています。（パスの指定方法を変えられる方法？）
CIの環境とローカル環境の違いですかね、、、

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
遅くなりましたが、現状を報告いたします。

- 本番環境のDBを最新のスキーマに更新し、ローカル環境ではビルドができることを確認
- あべみさんがご指摘されているRollupのbuildエラーが発生

```terminal
RollupError: "defineTaskAnswerFactory" is not exported by "src/__generated__/fabbrica/index.js", imported by "src/lib/services/answers.ts".
```

> CIの環境とローカル環境の違いってなにがあるのですかね、、、

answers.tsで、fabbricaのファイルを相対パスで参照しているところが影響している可能性はありそうでしょうか?

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

以下の問題のうち1つ目が解決できれば、2つ目の問題は回避できそうですが、1つ目のエラーの原因が不明という状況でしょうか?

- src/lib/services/answers.tsで、prisma.taskAnswer.createで答えを生成しようとすると、なぜか最初のプロパティだけ存在しないとエラーが出る（属性を追加・削除しても、最初の1つ目のみ）
- やむなく、defineTaskAnswerFactoryを使うと答えは生成できるものの、相対パスが影響しているのかCIでビルドが失敗する

**Comment by KATO-Hiro** [comment]
Rollupの公式ドキュメントに、今回のエラーに近い内容があるような気がしますが、いかがでしょうか?

https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
https://github.com/rollup/plugins/tree/master/packages/commonjs#custom-named-exports

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
一つ目に関してですが、prisma.taskanswerで実施する方法は試してみたのですが、エラー部分は自動採番や属性が足りない部分だと思います。
fabbricaの factoryは、seed.tsでも使っているのですが、まさにfactoryが、ない属性を勝手に作ってくれるんだと認識しています。factoryをつかうと全ての属性を入力しなくてよくて便利です。
自動生成のidも適当に作ってくれるので、出来ればfactoryを使いたいと思っています。

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
fabbricaを、lib以下に入れると、@libで絶対パスでアクセスができそうですが、
fabbricaの自動生成したものがsrc以下に来ることでデプロイ時にlintの対象になってしまいエラーになるようなメッセージも出ているので、この自動生成フォルダだけlint対象外になる設定があるのであれば、試してみたいです。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

教えていただき、ありがとうございます。

factoryの使用について、承知いたしました。

> fabbricaの自動生成したものがsrc以下に来ることでデプロイ時にlintの対象になってしまいエラーになるようなメッセージも出ているので、この自動生成フォルダだけlint対象外になる設定があるのであれば、試してみたいです。

お手数をお掛けしますが、試していただいてもよろしいでしょうか?

**Comment by prettyhappycatty** [comment]
これが気になる（メモ）

https://qiita.com/Uro3/items/d8e7382fb66935e532bd

**Comment by KATO-Hiro** [comment]
> これが気になる（メモ）
> 
> https://qiita.com/Uro3/items/d8e7382fb66935e532bd

調査していただき、ありがとうございます！

記事のプラグイン以外にも、以下のものもありそうです。
https://github.com/rollup/plugins/tree/master/packages/commonjs#custom-named-exports
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ありがとうございます。
この辺も気になっています。
https://31navi.com/not-able-to-prisma-seed

＞fabbricaの自動生成したものがsrc以下に来ることでデプロイ時にlintの対象になってしまいエラーになるようなメッセージも出ているので、この自動生成フォルダだけlint対象外になる設定があるのであれば、試してみたいです。

src/lib以下に入れて、@libでインポートしてもエラーでした。
rollupができないから、除外してね、と言われてるので除外して見たところ、ローカルでビルドが通らなかったです（必要なものを除外したら通らないですよね、、、）

**Comment by KATO-Hiro** [comment]
> rollupができないから、除外してね、と言われてるので除外して見たところ、ローカルでビルドが通らなかったです（必要なものを除外したら通らないですよね、、、）

少し前の状態では以下のような対処をしていたと思います。
.gitignoreに.fabbricaを追加しておくことでローカルに残しつつ、CIでは自動生成したもの使っていました。
（ただ、同フォルダは回答の更新で必要なので、現時点では利用できないような気がしています）

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ありがとうございます！
fabbricaのpreview用のビルド実績が今のところないということですね！
その方向で調べてみますれ

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 

 >error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:22
   | 
21 |   provider = "postgresql"
22 |   url      = env("DATABASE_URL")
   | 


すみません、このエラーって何が原因かわかりますでしょうか？
データベースのパスは、アプリの中で設定されているように思うのですが、なにか設定をいじるファイルを変更してしまったかな、、、？

**Comment by prettyhappycatty** [comment]
とりあえず、以下のバージョンで、fabbrica使わずに登録してみました。
（適当なidを取得するための関数を入れているのですが、衝突判定はしていないので変更必要です、、、）
ただ、上述の、DBURLのエラーが消えなくて困っています。
https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/commit/795f9c8610976a0ac2629b889cb65f8397108a33

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
返信が遅くなり、すみません🙇。

ビルドエラーの修正にご対応いただき、ありがとうございます！
暫定的な対応についても、承知いたしました。


DBのURLエラーについて調査・修正を試みたいと思います。
直前で以下の内容が表示されていますので、本番環境に最新のスキーマが反映されていない状態だと予想しています。

```md
PrismaClientInitializationError: 
Invalid `prisma.submissionStatus.findMany()` invocation:
```

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ありがとうございます。
もしかしてなのですが、前回のマージ時にsubmissionstatusテーブルを追加していて、今回さらにsubmissionstatusテーブルに属性を追加しています。
デフォルト属性を入れずに必須の属性を入れてしまっているので、今入っているデータに対してエラーが出てしまうので適用できていない可能性があるかと思いました。
default属性を追加してみます。

**Comment by prettyhappycatty** [comment]
本番のsubmission_statusとtask_answerテーブルのデータを削除してみていただくことは可能でしょうか？

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
教えていただき、ありがとうございます！

> 本番のsubmission_statusとtask_answerテーブルのデータを削除してみていただくことは可能でしょうか？

承知いたしました。対応させていただきたいと思います。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty
 
> 本番のsubmission_statusとtask_answerテーブルのデータを削除してみていただくことは可能でしょうか？

本番環境のスキーマが最新であることを確認した上で、2つのテーブルのデータを削除してみました。
また、本番環境のDBのURLも有効であると思います。
しかし、ビルドは相変わらず失敗しているようです。

上記のURLに関するエラーの直前で、以下のような内容が表示されています。
可能性としてprisma/seed.tsのaddSubmissionStatuses()か、lib/service/submission_status.tsのgetSubmissionStatusMapWithId()もしくはgetSubmissionStatusMapWithName()のfindManyが関係しているのではないかと思いますが、いかがでしょうか?

```terminal
PrismaClientInitializationError: 
Invalid `prisma.submissionStatus.findMany()` invocation:
```

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
seedのほうが、prisma.で、ほかのはclient.だったので、seedのほうを削除してみたのですがエラーメッセージ変わらずです

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
> getSubmissionStatusMapWithId()もしくはgetSubmissionStatusMapWithName()
こっちをmock（サンプルデータのjson）に変えたらうまくいきました！

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
回答状況と問題の紐付けの実装およびビルドエラーの修正、大変お疲れ様です！！！

デフォルトの回答状況の実装を最優先し、カスタマイズについてはこれから実装するという認識でよろしいでしょうか?

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
カスタマイズについては別issueで良いのかなと思いますがいかがでしょうか。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

> カスタマイズについては別issueで後回しで良いのかなと思いますがいかがでしょうか。

私もそのように思います。

> （タスクの保存でsubmissionStatusテーブルとつなぐことについては、現段階ではこれでいいかもしれないのですが、リリース時にはデータベースとつないだほうがいいと思います。taskAnswerデータが登録され始めると移行が面倒そう）

リリース前には解決したいですね。

> 次の優先度が高いのは、↓の#327かと思っています。

本アプリの重要な機能の一つだと認識しています。

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
seed.tsだけ戻しました。（IDの重複を避けたい件と、ステータスをDBに繋ぐ、ステータスをカスタマイズ可能にする、は別issueにします）
問題なければマージお願いしたいです。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

修正ありがとうございます！

#342 をマージいたしました。

> IDの重複を避けたい件と、ステータスをDBに繋ぐ、ステータスをカスタマイズ可能にする、は別issueにします
承知いたしました！

引き続き、よろしくお願いいたします。
