### ISSUE TITLE
APIからデータを取得できるようにしましょう/ ユーザーのvalidateをできるようにしましょう

### ISSUE THREAD

**Issue by prettyhappycatty** [AtCoder-NoviSteps/AtCoderNoviSteps#331]
## Description / 説明
- [x] ユーザページの作成（認証をするためのUI）
   - [x] 画面の用意（ログイン中の人とそれ以外の人の表示を分ける）
   - [x] リクエスト
   - [x] userテーブルにatcoderのidとtokenを保持できるようにする
- [x] ユーザ認証
- [x] 問題データの取得

## Motivation / 動機

- ユーザ認証
  - ユーザIDにAtCoderのIDを持たせたい。（インポート機能等を使って登録する場合、確実に本人のIDであるようにしたい）
  
-  問題データの取得
   - 毎週問題が追加されるため、いい感じに（できれば自動で）追加できるようにしたい 

## Other notes / その他
- APIとの接続について
  - DBからデータを取得するのと似た感じで、APIからデータを取得できるといい
  - リクエストを投げ過ぎないようにしたい
        
- 画面（予定）
    - users/[id] ・・・atcoderのprofileページみたいにする。自分のidのものだけ、users/editにいくボタンを表示する
       - アイコン、ユーザID、などを表示する？
       - taskAnswerの日付降順（最近記録したものがわかる）などを表示する？
    - users/edit ・・・ログイン中のユーザ設定ができるページとする。以下のタブを用意する。
        -  基本・・・ユーザIDやアイコンを変更できる。
        - ステータス・・・ステータスをカスタマイズできる（submissionStatusの編集もここで。）
        - AtCoder連携・・・AtCoderのusernameの修正とvalidateができる
        - インポート・・・・AtCoderのvalidateがされている場合だけ表示される。AtCoderのsubmissionを検索して、入力がないtaskに対してtaskAnswerをインポートできる
        - 退会・・・・退会処理（ユーザ削除）ができる

**Comment by KATO-Hiro** [comment]
問題データの追加に関しては、将来的にCI + 定期実行で実現できると良さそうです。

ある程度の問題がアプリで収録できた段階以降では、ProblemsのコンテストAPIにあるepoch_second?とDBで最も新しいデータを比較するような形をイメージしていますが、いかがでしょうか?

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 

>ある程度の問題がアプリで収録できた段階以降では、ProblemsのコンテストAPIにあるepoch_second?とDBで最も新しいデータを比較するような形をイメージしていますが、いかがでしょうか?

問題なら、週あたり12個くらいの増加？なので、数は知れてるかなという気がします。

submissionをクロールしようと思うと量が多いし一度に500件くらいしか取れないので、epoch_secondが必要になると思います。

今回は、ユーザーのvalidateで、auth-apiを叩きたくなったので、
ついでにAtcoderProblemsServiceみたいなサービス層のファイルを作って、問題データを取得するサービスも一緒に入れてしまおうかと思ってissueにしました。

**Comment by prettyhappycatty** [comment]
user-authですが、一度ABCトーナメントで使った時には以下の流れでした。（うろ覚え）
・ABCトーナメントで、authトークンのようなものを発行
・AtCoderのプロフィールの所属を、authトークンの文字列に変更
・ABCトーナメントで、validateか何かのボタンを押す

なので、
ユーザページの認証画面で、authトークン発行ボタン、validateボタンを準備し、
それぞれのボタンをおしたときに、authトークンの発行と、validateのサービスを呼び出す仕組みを準備しようと思っています。
また、userテーブル？keyテーブル？にvalidateすみのatcoderユーザーネームを保存する属性を用意しようと思います。

**Comment by KATO-Hiro** [comment]
> 今回は、ユーザーのvalidateで、auth-apiを叩きたくなったので、 ついでにAtcoderProblemsServiceみたいなサービス層のファイルを作って、問題データを取得するサービスも一緒に入れてしまおうかと思ってissueにしました。 週次で定期実行する際に、そのサービスを呼んでもらえばいい状態にしておこうと思います。

外部サービスのへのアクセス部分を明示的に分けておくと、プロジェクトの管理もしやすそうですね！

**Comment by prettyhappycatty** [comment]
#329 

ユーザーページの作成
https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/pull/329/files#diff-c56732c7e83a9915726acba95654a6704f4d8ea6141b85f505e80b90775863ca

問題取得
https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/pull/329/files#diff-f32c4f7d3760dc3034020ca129168bd00c437f40dd109373196281a0e66434ce

画面が追いついていないので動作確認は後ほど、、、
ユニットテストで実行しようとしたけどこちらもうまくやり方が分からず。
もしわかれば教えてください。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

外部のREST APIへの通信を含むような単体テストには、ローカル環境でリクエスト・レスポンスを保存・再現するというのが一つの方法としてあるのではないかと思います。

このような機能をサポートしたライブラリ(vcr)が各言語で用意されているようです。
具体的には、ユニットテストの初回だけHTTPリクエストの実行・レスポンスの受け取りと保存を行い、2回目以降は保存したリクエスト・レスポンスを再利用してテストします。

また、VCRライブラリの選定も必要になるかと思います。

VCR本家
https://github.com/vcr/vcr

本家で紹介されているNode.jsへの移植版（継続してメンテナンスされるかやや不安な印象がありますが、いかがでしょうか?）
https://github.com/ijpiantanida/talkback


https://www.techmatrix.co.jp/product/soatest_virtualize/rest_api_test.html
https://zenn.dev/sumiren/articles/aa0ba5ae12ad2e

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ご紹介ありがとうございます。
coverage-c8でできるはずだろうとは思っているのですが、
対象のプログラムのインポートのやり方が分からず困っている感じです。
src/test/example.test.txからsrc/lib/component/*ApiServices.tsのメソッドを呼んでテストしたいのですが、
../lib/component/*ApiServices.tsではアクセスできなそうで（エラーの下線が出てしまう）

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

以下のようなエイリアス（$lib）を登録していますので、試していただけますでしょうか?

import { getTasks } from '$lib/services/problemsApiService';

**Comment by prettyhappycatty** [comment]
メモ

- atcoder-authがどうも動いていないみたい
    - →個人所有の環境に一時的にプロフィールのデータを取得できる仕組みを配置。ちゃんとするならaws lambdaとかに移したほうが多分いい。（https://prettyhappy.sakura.ne.jp/php_curl/index.php?user=meowmeowcats）

- 画面（予定）
    - users/[id] ・・・atcoderのprofileページみたいにする。自分のidのものだけ、users/editにいくボタンを表示する
       - アイコン、ユーザID、などを表示する？
       - taskAnswerの日付降順（最近記録したものがわかる）などを表示する？
    - users/edit/[id] ・・・ユーザ設定ができるページとする。以下のタブを用意する。
        -  基本・・・ユーザIDやアイコンを変更できる。
        - ステータス・・・ステータスをカスタマイズできる
        - AtCoder連携・・・AtCoderのusernameとvalidateができる
        - インポート・・・・AtCoderのvalidateがされている場合だけ表示される。AtCoderのsubmissionを検索して、入力がないtaskに対してtaskAnswerをインポートできる
        - 退会・・・・退会処理（ユーザ削除）ができる

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
外部APIの調査およびUIの仕様を言語化していただき、ありがとうございます！

> ちゃんとするならaws lambdaとかに移したほうが多分いい。

お恥ずかしい話ではありますが、AWSは名前を聞いたことがある程度です。
求められる要件次第だとは思いますが、必要に応じて導入する場合もあると理解しました。


詳しい仕様を確認する必要がありますが、Vercelにもサーバレス関数（PHPランタイムを含む）がサポートされているようです（GitHubなどのホスティングサービスに該当スクリプトをアップロードして、Vercelと連携すれば利用できそうです）。

 
https://vercel.com/docs/functions/serverless-functions/runtimes#community-runtimes

もしくは、アプリ内でAtCoderユーザの連携とvalidateを実行するAPIを作成する方法もあるかもしれません。

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
lambdaにこだわりませんが、現在のアプリの中にpuppeteer（クローリングできるもの）を入れようとしたらうまく入らなかったので、とりあえず簡易的に別でAPIとして用意してみました。
PHPの簡単なプログラムなので、おっしゃるとおり、PHPが実行できてWebサーバであればできます。

私の環境で作ってしまっているので、共用でメンテできる場所に置きたい＆どのくらいリクエストさばけるか不安＆できればNoviStepアプリからのリクエストしか受け付けたくない、みたいな感じです。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
返信が遅くなり、すみません。

APIを用意していただき、ありがとうございます！！

> このAPIは私のサーバ環境で作ってしまっているので、共用でメンテできる場所に置きたい＆どのくらいリクエストさばけるか不安＆できればNoviStepアプリからのリクエストしか受け付けたくない、みたいな感じです。

一例として、以下のような方法はいかがでしょうか?

- APIのソースコード: NoviStepアカウントの（private）リポジトリに配置
- サーバ: 私のVercelアカウントと上記のリポジトリを連携し、ホスティング
  - Serverless Function もしくは Edge Functionとすると良さそう（両者の違いについては学習が必要だと思っています）
    - https://note.com/libproc/n/n10dd8760d530
    - https://vercel.com/docs/limits/overview#included-usage
- リクエストの制限: CORSの設定で、本番環境・ローカル環境のURLを指定

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
APIのソースコードをアップロードしていただき、ありがとうございます！
別Issueで対応する点についても承知いたしました。
