### ISSUE TITLE
ER図を継続更新していきたい

### ISSUE THREAD

**Issue by prettyhappycatty** [AtCoder-NoviSteps/AtCoderNoviSteps#352]
## Description / 説明

- https://dev.classmethod.jp/articles/prisma_er_diagram_auto_generation/

## Motivation / 動機

- いまの設計どうなってたっけ？→discordみる
- いまの実装どうなってたっけ？→prismaファイル見る

後者をER図で見たいなと思ったら、継続的にgenerateする仕組みがあるらしいことがわかったので、入れられると良いなと。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
ありがとうございます！！
Ver2.0から大きく変更した点もあるため、随時更新できるようになるとメンバーの情報共有や開発がよりスムーズになると思います。
