### ISSUE TITLE
CI: ステージング環境を用意しましょう

### ISSUE THREAD

**Issue by KATO-Hiro** [AtCoder-NoviSteps/AtCoderNoviSteps#362]
## WHY

- CIのpreview環境では、本番環境と同じDBが使われている
  - ステージング環境が用意できていないため、やむなく 
- このため、DBのスキーマを変更するたびに、手動で追従する必要がある
- 上記の作業ができない状態だとCIが失敗する

## 実施した内容

- デフォルトのブランチを`staging`に変更
- DBをそれぞれの環境に独立に用意
  - preview: ステージング用のDBを用意して、`staging`ブランチと関連付け
    - カスタムドメインで閲覧できるように
  - production: 本番環境のDBをこれまで通り使用(`main`ブランチ)
- CIを一部変更
  - スキーマの変更があった場合は、各環境で自動的に追従
  - マイグレーションが失敗したら、CIが止まるようになっている

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
本番環境（ステージング環境）のDBをどこから見に行けるのか知りたいです。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
私が登録しているsupabaseのアカウントから開発メンバーとしての招待メールを送信し、あべみさんが承認していただくと、DBを閲覧・編集できるようです。
メールアドレスを教えていただけますでしょうか?

https://supabase.com/docs/guides/platform/access-control

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
こちらのアドレスにいただけますか？
よろしくお願いします。
https://discord.com/channels/1142833143229980812/1143159385342890034/1184487572236410911

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 

帰宅しだい、送付させていただきたいと思います。
招待の有効期限が24時間らしく、もし期限切れの場合は改めてご一報いただけると幸いです。

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
遅くなりましたが、supabaseのへの招待メールを送付いたしました。

プロジェクト名は、AtCoderで登録しています。

データベースの閲覧・編集が可能か、ご確認いただけますでしょうか?

**Comment by prettyhappycatty** [comment]
@KATO-Hiro 
ありがとうございます。
参加できたと思います！

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
ご確認いただき、ありがとうございます！

**Comment by KATO-Hiro** [comment]
参考資料です
https://user-first.ikyu.co.jp/entry/2023/12/16/112705

**Comment by KATO-Hiro** [comment]
https://zenn.dev/keitakn/articles/nextjs-vercel-create-staging

**Comment by KATO-Hiro** [comment]
Cloudflare: ドメインの取得方法
https://zenn.dev/pino0701/articles/cloudflare_registrar

初期設定
https://zenn.dev/keitakn/articles/add-cloudflare-domain-to-vercel

**Comment by KATO-Hiro** [comment]
develop branchをメインブランチにしたときに、mainの誤削除を防ぐ方法

https://fwywd.com/tech/github-switch-default-branch

**Comment by KATO-Hiro** [comment]
本番環境のマイグレーションで、_prisma_migrationsテーブルが必要なため、以下の記事を参考にしました

- マイグレーションファイルを一旦廃棄
- 0_initフォルダを作成
- 現時点でのprisma/schema.prismaからSQLを自動的に生成
- この状態をベースとすることを本番環境で設定

https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/baseline-your-database-typescript-postgresql#review-the-migration
