### ISSUE TITLE
左上アイコン画像がうまく表示できないページがある

### ISSUE THREAD

**Issue by prettyhappycatty** [AtCoder-NoviSteps/AtCoderNoviSteps#370]
## Summary / 概要

- 左上のアイコン画像のリンクが切れているページがある

## Steps to reproduce / 再現方法

以下のページで起こっている

- /problems/[id]
- /users/

### environments

- Desktop (please complete the following information):

  OS: Mac
  Browser Chrome
  Version 120.0.6099.129

## Expected behavior / 期待される挙動

- 画像が表示される

### Screenshots

<img width="1330" alt="スクリーンショット 2023-12-26 21 51 36" src="https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/assets/1721854/a5e15ae2-fc4e-4527-bdc4-befe1146d038">

## Other notes / その他

- Add any other context about the problem here.
- Will you try to create a pull request?
  - yes / no

**Comment by KATO-Hiro** [comment]
@prettyhappycatty 
ご報告いただき、ありがとうございます！

ときどき発生しており、画面をリロードすれば解消できるものだと認識しています。
（SvelteおよびSvelte Kitの基本的な機能で対処できそうな気もしています。）

**Comment by prettyhappycatty** [comment]
多分、画像の指定が相対パスなせいだと思ってます。

**Comment by KATO-Hiro** [comment]
faviconの差し替えとともにパスを修正しました。正しく表示されていると思います。
