### ISSUE TITLE
存在していない Xアカウントへのリンクがある

### ISSUE THREAD

**Issue by siman-man** [AtCoder-NoviSteps/AtCoderNoviSteps#661]
## Summary / 概要

「開発・運営メンバー」の一覧の中に各個人の SNS へのリンクが付与されているのですが、その中の一人の `あべみ` さんのリンクが存在しない Xアカウントへのリンクになっています。

## Steps to reproduce / 再現方法

1. `あべみ` さんのリンクをクリックする
2. 存在しない Xアカウントへのリンクに飛ばされる

## Expected behavior / 期待される挙動

他の方のリンクを見る限り X アカウントへのリンクが正しいと思うので

https://twitter.com/cats0830v

に飛ぶのが期待されます。

Github のページに飛ばすのであれば

https://github.com/prettyhappycatty

に飛ぶことが期待されます。

## Actual behavior / 実際の挙動

https://twitter.com/prettyhappycatty に飛ばされます。

### Screenshots

1.  `あべみ` さんのリンクをクリックする

<img width="230" alt="Screenshot 2024-04-10 at 0 28 02" src="https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/assets/1725620/3da47ea5-15a3-461e-babc-82d0b3a0a8fc">

2. 存在しないアカウントに飛ばされる

<img width="671" alt="Screenshot 2024-04-10 at 0 38 25" src="https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/assets/1725620/59ffb7ab-3259-4bf1-a1eb-e8d4d9163fb8">

## Other notes / その他

自分が確認した限りでは 2箇所で問題がありそうです

<img width="661" alt="Screenshot 2024-04-10 at 0 39 19" src="https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/assets/1725620/1cf74118-4b68-44e7-9337-0067cbe44ce1">

**Comment by KATO-Hiro** [comment]
教えていただき、ありがとうございます！
修正します。
