### ISSUE TITLE
登録ページとログインページで、"👁️"ボタンがフォーム送信の挙動をする

### ISSUE THREAD

**Issue by roumcha** [AtCoder-NoviSteps/AtCoderNoviSteps#818]
## Summary / 概要

ログイン画面及びアカウント作成画面で👁️（パスワードの表示/非表示）ボタンを押すと、ログインやアカウント作成が確定されてしまいます。

## Steps to reproduce / 再現方法

1. ログイン画面に行く
2. IDとパスワードを入力し、👁️ボタンを押す

### environments

- Desktop:

  OS: Windows 11
  Browser: Microsoft Edge
  Version: 125.0.2535.51

**Comment by KATO-Hiro** [comment]
Issueを作成していただき、ありがとうございます。

手元の環境で確認および修正をしたいと思います。
よろしくお願いいたします。
